"use client";
import { useEffect, useState } from "react";
import "../globals.css";
const axes=["A PEOPLE","B PRINCIPLES","C PATTERNS","D HISTORY","E THEORY","F EVIDENCE","G VIEWS","H ME"];
type Row=Record<string,unknown>;
export default function InvestmentOsPage(){
 const [data,setData]=useState<{규칙라이브러리?:Row[];인물알고리즘?:Row[];원칙지도?:Row[];error?:string}>({});
 const [person,setPerson]=useState("전체"),[layer,setLayer]=useState("전체");
 const [q,setQ]=useState("");
 useEffect(()=>{fetch("/api/knowledge-universe").then(r=>r.json()).then(setData).catch(()=>setData({error:"Knowledge Universe를 불러오지 못했습니다."}))},[]);
 const rows=(data.규칙라이브러리||[]).filter(r=>person==="전체"||String(r["인물"]||"")===person).filter(r=>layer==="전체"||String(r["레이어"]||"")===layer);
 const people=Array.from(new Set((data.규칙라이브러리||[]).map(r=>String(r["인물"]||"")).filter(Boolean)));
 return <main className="os-page"><a className="os-back" href="/">← AI 투자 도구 MASTER</a><header className="os-intro"><span>INVESTMENT DECISION OS · V1.1</span><h1>정보를 모으기 위해서가 아니라,<br/><em>같은 순서로 판단하기 위해서입니다.</em></h1><p>지식을 지혜로 바꾼다.</p></header><section className="os-flow"><div><b>NOW</b><span>→</span><b>SIGNAL</b><span>→</span><b>ME</b><span>→</span><b>DO</b></div><small>COLLECT → DISTILL → CONNECT → DECIDE → LEARN ↺</small></section><section className="os-panel"><div className="os-panel-heading"><div><span>DECIDE</span><h2>지금, 무엇을 판단하나요?</h2></div></div><textarea className="os-decide-input" value={q} onChange={e=>setQ(e.target.value)} placeholder="예: 지금 이 아파트를 사도 될까?"/><p className="os-hint">질문을 적고 관련 지식 카드를 아래에서 확인하세요. 판단 데이터는 이 브라우저에만 남습니다.</p></section><section className="os-universe"><div className="os-panel-heading"><div><span>KNOWLEDGE UNIVERSE</span><h2>규칙 라이브러리 · 인물 알고리즘 · 원칙 지도</h2></div><small>{data.error||`규칙 ${rows.length}개`}</small></div><div className="os-filters"><select value={person} onChange={e=>setPerson(e.target.value)}><option>전체</option>{people.map(p=><option key={p}>{p}</option>)}</select><select value={layer} onChange={e=>setLayer(e.target.value)}><option>전체</option>{Array.from(new Set((data.규칙라이브러리||[]).map(r=>String(r["레이어"]||"")).filter(Boolean))).map(l=><option key={l}>{l}</option>)}</select></div><div className="axis-grid">{axes.map(a=><article key={a}><b>{a.split(" ")[0]}</b><h3>{a.slice(2)}</h3><p>{a.startsWith("F")?"현재시장 데이터와 근거":"지식과 경험을 구조화"}</p></article>)}</div><div className="ku-cards">{rows.slice(0,24).map((r,i)=><article key={String(r.id||i)}><span>{String(r["근거수준"]||"KNOWLEDGE")}</span><h3>{String(r["Rule ID/제목"]||r["원칙/쟁점 ID"]||r["인물"]||"지식 카드")}</h3><p>{String(r["판단"]||r["설명"]||r["상황"]||"")}</p><small>{String(r["인물"]||"")} · {String(r["레이어"]||"")}</small></article>)}</div></section><section className="os-journal"><span>LEARN</span><h2>판단은 기록할 때 자산이 됩니다.</h2><p>결과와 평가를 남기면 다음 판단에 활용할 수 있습니다.</p></section></main>;
}
