"use client";
import {useEffect,useMemo,useState} from "react";
const ORDER=["서울","경기","인천","부산","대구","광주","대전","울산","세종","강원","충북","충남","전북","전남","경북","경남","제주"];
const NEW_SET=new Set(["세종","강원","충북","충남","전북","전남","경북","경남","제주"]);
function n(v){const x=Number(v);return Number.isFinite(x)?x:null}
function pct(v){const x=n(v);return x==null?"-":`${x>0?"+":""}${x.toFixed(2)}%`}
function idx(v){const x=n(v);return x==null?"-":x.toFixed(2)}
function cls(v){const x=n(v);return x==null||x===0?"flat":x>0?"up":"down"}
function Chart({weeks}){const rows=weeks||[];const vals=rows.flatMap(r=>[n(r.saleRate),n(r.jeonseRate)]).filter(v=>v!=null);if(vals.length<2)return <div className="emptyChart">차트 데이터 없음</div>;const W=760,H=185,L=44,R=12,T=10,B=28;let lo=Math.min(...vals),hi=Math.max(...vals);const pad=Math.max((hi-lo)*.2,.05);lo-=pad;hi+=pad;const span=hi-lo||1;const x=i=>L+(W-L-R)*(i/Math.max(rows.length-1,1));const y=v=>T+(H-T-B)*(1-(v-lo)/span);const points=k=>rows.map((r,i)=>n(r[k])==null?null:`${x(i)},${y(n(r[k]))}`).filter(Boolean).join(" ");const ticks=[0,.25,.5,.75,1].map(t=>lo+(hi-lo)*t);return <svg viewBox={`0 0 ${W} ${H}`} preserveAspectRatio="none">{ticks.map((v,i)=><g key={i}><line className="grid" x1={L} x2={W-R} y1={y(v)} y2={y(v)}/><text className="axis" x="3" y={y(v)+3}>{v.toFixed(2)}</text></g>)}<polyline className="saleLine" points={points("saleRate")}/><polyline className="jeonseLine" points={points("jeonseRate")}/>{rows.map((r,i)=>(i%3===0||i===rows.length-1)?<text key={i} className="axis" x={x(i)-15} y={H-7}>{r.date?.slice(5)||""}</text>:null)}</svg>}
function RegionSection({region}){const latest=region.weeks?.at(-1);const sorted=[...(region.districts||[])].sort((a,b)=>(n(b.weeks?.at(-1)?.saleRate)??-999)-(n(a.weeks?.at(-1)?.saleRate)??-999));return <section className={`regionCard ${NEW_SET.has(region.name)?"newRegion":""}`}><div className="regionHead"><div><h2>{region.name}</h2><p>{sorted.length}개 세부지역 · 매매/전세 동시 비교</p></div><div className="regionNow"><span className={cls(latest?.saleRate)}>매매 {pct(latest?.saleRate)}</span><span className={cls(latest?.jeonseRate)}>전세 {pct(latest?.jeonseRate)}</span></div></div><div className="chartWrap"><div className="legend"><span className="saleKey">매매</span><span className="jeonseKey">전세</span><span>최근 13주 상승률</span></div><Chart weeks={region.weeks}/></div><div className="tableWrap"><table><thead><tr><th>지역</th><th>매매 이번주</th><th>매매 지수</th><th>전세 이번주</th><th>전세 지수</th></tr></thead><tbody>{sorted.map(d=>{const w=d.weeks?.at(-1);return <tr key={`${region.name}-${d.name}-${d.parent||""}`}><td><strong>{d.name}</strong>{d.parent&&<small>{d.parent}</small>}</td><td className={cls(w?.saleRate)}>{pct(w?.saleRate)}</td><td>{idx(w?.saleIndex)}</td><td className={cls(w?.jeonseRate)}>{pct(w?.jeonseRate)}</td><td>{idx(w?.jeonseIndex)}</td></tr>})}</tbody></table></div></section>}
export default function Home(){const[data,setData]=useState(null),[error,setError]=useState("");async function load(){try{setError("");const r=await fetch("/api/reb",{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"데이터 오류");setData(j)}catch(e){setError(e.message||String(e))}}useEffect(()=>{load();const t=setInterval(()=>{const p=new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Seoul",weekday:"short",hour:"2-digit",minute:"2-digit",hour12:false}).formatToParts(new Date());const g=k=>p.find(x=>x.type===k)?.value;const wd=g("weekday"),h=+g("hour"),m=+g("minute");if(wd==="Thu"&&((h===14&&m>=25)||(h===15&&m<=10)))load()},60000);return()=>clearInterval(t)},[]);const ordered=useMemo(()=>ORDER.map(name=>data?.regions?.find(r=>r.name===name)).filter(Boolean),[data]);return <main><header className="hero"><div><div className="eyebrow">R-ONE · WEEKLY APARTMENT PRICE TREND</div><h1>주간 아파트 가격동향</h1><p>서울·경기·인천·광역시뿐 아니라 세종과 8개 도까지 한 페이지에서 아래로 쭉 봅니다.</p></div><div className="dateBox"><b>{data?.latestDate?`조사기준일 ${data.latestDate}`:"최신 자료 불러오는 중"}</b>{data?.releaseDate&&<span>공표일 {data.releaseDate}</span>}</div></header>{error&&<div className="error">{error}</div>}{!data?<div className="loading">한국부동산원 전국 시·군·구 데이터를 불러오는 중…</div>:<><div className="jump">{ORDER.map(x=><a key={x} href={`#r-${x}`} className={NEW_SET.has(x)?"added":""}>{x}</a>)}</div>{ordered.map(r=><div id={`r-${r.name}`} key={r.name}><RegionSection region={r}/></div>)}</>}<footer>출처: 한국부동산원 R-ONE · 매주 발표된 최신 공개자료를 자동 재확인합니다.</footer></main>}
