import {NextResponse} from "next/server";
export const dynamic="force-dynamic";
const BASE="https://www.reb.or.kr/r-one/openapi/SttsApiTblData.do";
const SALE="T244183132827305", JEONSE="T247713133046872";
const TARGETS=["서울","경기","인천","부산","대구","광주","대전","울산","세종","강원","충북","충남","전북","전남","경북","경남","제주"];
function isoWeekCode(d){const x=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()));const day=x.getUTCDay()||7;x.setUTCDate(x.getUTCDate()+4-day);const y0=new Date(Date.UTC(x.getUTCFullYear(),0,1));const w=Math.ceil((((x-y0)/86400000)+1)/7);return `${x.getUTCFullYear()}${String(w).padStart(2,"0")}`}
function mondayKST(){const now=new Date(Date.now()+9*3600000);const y=now.getUTCFullYear(),m=now.getUTCMonth(),d=now.getUTCDate(),wd=now.getUTCDay()||7;return new Date(Date.UTC(y,m,d-(wd-1)))}
function releaseDate(monday){const x=new Date(monday.getTime()+3*86400000);return `${x.getUTCFullYear()}-${String(x.getUTCMonth()+1).padStart(2,"0")}-${String(x.getUTCDate()).padStart(2,"0")}`}
function rowsOf(j){if(!j||typeof j!=="object")return[];if(Array.isArray(j)){for(const v of j){if(v&&Array.isArray(v.row))return v.row;const r=rowsOf(v);if(r.length)return r}return[]}if(Array.isArray(j.row))return j.row;for(const v of Object.values(j)){const r=rowsOf(v);if(r.length)return r}return[]}
async function fetchWeek(id,code,key){const u=new URL(BASE);for(const[k,v]of Object.entries({KEY:key,Type:"json",STATBL_ID:id,DTACYCLE_CD:"WK",START_WRTTIME:code,END_WRTTIME:code,pIndex:1,pSize:1000}))u.searchParams.set(k,String(v));const r=await fetch(u,{cache:"no-store"});const t=await r.text();let j=null;try{j=JSON.parse(t)}catch{}return rowsOf(j)}
function rate(a,b){a=Number(a);b=Number(b);return Number.isFinite(a)&&Number.isFinite(b)&&b!==0?Math.round(((a/b-1)*100)*100)/100:null}
function pathOf(r){return String(r.CLS_FULLNM||r.CLS_NM||"").replace(/\s+/g," ").trim()}
function partsOf(r){return pathOf(r).split(">").map(s=>s.trim()).filter(Boolean)}
function groupOf(r){const p=partsOf(r);for(const g of TARGETS){if(p.includes(g))return g}if(p.includes("전남광주")&&p.includes("광주"))return"광주";return null}
function findTop(rows,g){const c=rows.filter(r=>groupOf(r)===g&&String(r.CLS_NM||"").trim()===g);if(c.length)return c.sort((a,b)=>partsOf(a).length-partsOf(b).length)[0];const c2=rows.filter(r=>groupOf(r)===g);return c2.sort((a,b)=>partsOf(a).length-partsOf(b).length)[0]||null}
function buildLeafIds(rows,g){const scoped=rows.filter(r=>groupOf(r)===g).map(r=>({...r,_p:pathOf(r)}));const paths=scoped.map(r=>r._p);return scoped.filter(r=>{const nm=String(r.CLS_NM||"").trim();if(nm===g)return false;if(/권$|지역$/.test(nm))return false;return !paths.some(p=>p!==r._p&&p.startsWith(r._p+">"))}).map(r=>String(r.CLS_ID))}
function mapRows(rows){return new Map(rows.map(r=>[String(r.CLS_ID),r]))}
export async function GET(){try{const key=process.env.RONE_API_KEY||"";if(!key)throw new Error("RONE_API_KEY 미연결");let monday=mondayKST(),latestSale=[];for(let i=0;i<5;i++){latestSale=await fetchWeek(SALE,isoWeekCode(monday),key);if(latestSale.length)break;monday=new Date(monday.getTime()-7*86400000)}if(!latestSale.length)throw new Error("최근 주간 매매자료를 찾지 못했습니다.");const dates=[];for(let i=14;i>=0;i--)dates.push(new Date(monday.getTime()-i*7*86400000));const codes=dates.map(isoWeekCode);const [sales,jeonses]=await Promise.all([Promise.all(codes.map(c=>fetchWeek(SALE,c,key))),Promise.all(codes.map(c=>fetchWeek(JEONSE,c,key))]);const sm=sales.map(mapRows),jm=jeonses.map(mapRows);const latestRows=sales.at(-1),latestJ=jeonses.at(-1);const regions=[];for(const g of TARGETS){const top=findTop(latestRows,g)||findTop(latestJ,g);if(!top)continue;const topId=String(top.CLS_ID);const weeks=[];for(let i=1;i<codes.length;i++){const s=sm[i].get(topId),ps=sm[i-1].get(topId),j=jm[i].get(topId),pj=jm[i-1].get(topId);weeks.push({code:codes[i],date:s?.WRTTIME_DESC||j?.WRTTIME_DESC||codes[i],saleIndex:s?Number(s.DTA_VAL):null,jeonseIndex:j?Number(j.DTA_VAL):null,saleRate:s&&ps?rate(s.DTA_VAL,ps.DTA_VAL):null,jeonseRate:j&&pj?rate(j.DTA_VAL,pj.DTA_VAL):null})}const leafIds=buildLeafIds(latestRows,g);const districts=[];for(const id of leafIds){const cur=sm.at(-1).get(id)||jm.at(-1).get(id);if(!cur)continue;const full=partsOf(cur);const name=String(cur.CLS_NM||full.at(-1)||"").trim();let parent=full.length>1?full.at(-2):null;if(parent===g||/권$|지역$/.test(parent||""))parent=null;const dWeeks=[];for(let i=1;i<codes.length;i++){const s=sm[i].get(id),ps=sm[i-1].get(id),j=jm[i].get(id),pj=jm[i-1].get(id);dWeeks.push({code:codes[i],date:s?.WRTTIME_DESC||j?.WRTTIME_DESC||codes[i],saleIndex:s?Number(s.DTA_VAL):null,jeonseIndex:j?Number(j.DTA_VAL):null,saleRate:s&&ps?rate(s.DTA_VAL,ps.DTA_VAL):null,jeonseRate:j&&pj?rate(j.DTA_VAL,pj.DTA_VAL):null})}districts.push({name,parent,weeks:dWeeks})}regions.push({name:g,weeks,districts})}return NextResponse.json({latestDate:regions[0]?.weeks?.at(-1)?.date||null,releaseDate:releaseDate(monday),regions})}catch(e){return NextResponse.json({error:e.message||String(e)},{status:500})}
